@API_HostAddress = http://localhost:5057

GET {{API_HostAddress}}/api/client/AllClients

###

POST {{API_HostAddress}}/api/client
Content-Type: application/json

{
  //ClientCreateRequestDTO
}

###

DELETE {{API_HostAddress}}/api/client

###
